//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.15 at 06:36:01 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.idpf.org/2007/opf/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.idpf._2007.opf;
