//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.03 at 11:51:35 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kr.co.hancom.hwpml._2011.paragraph package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kr.co.hancom.hwpml._2011.paragraph
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Switch }
     * 
     */
    public Switch createSwitch() {
        return new Switch();
    }

    /**
     * Create an instance of {@link Case }
     * 
     */
    public Case createCase() {
        return new Case();
    }

    /**
     * Create an instance of {@link Default }
     * 
     */
    public Default createDefault() {
        return new Default();
    }
	
	/**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link Run }
     * 
     */
    public Run createRun() {
        return new Run();
    }

    /**
     * Create an instance of {@link SecPr }
     * 
     */
    public SecPr createSecPr() {
        return new SecPr();
    }

    /**
     * Create an instance of {@link Grid }
     * 
     */
    public Grid createGrid() {
        return new Grid();
    }

    /**
     * Create an instance of {@link StartNum }
     * 
     */
    public StartNum createStartNum() {
        return new StartNum();
    }

    /**
     * Create an instance of {@link Visibility }
     * 
     */
    public Visibility createVisibility() {
        return new Visibility();
    }

    /**
     * Create an instance of {@link LineNumberShape }
     * 
     */
    public LineNumberShape createLineNumberShape() {
        return new LineNumberShape();
    }

    /**
     * Create an instance of {@link PagePr }
     * 
     */
    public PagePr createPagePr() {
        return new PagePr();
    }

    /**
     * Create an instance of {@link Margin }
     * 
     */
    public Margin createMargin() {
        return new Margin();
    }

    /**
     * Create an instance of {@link FootNotePr }
     * 
     */
    public FootNotePr createFootNotePr() {
        return new FootNotePr();
    }

    /**
     * Create an instance of {@link AutoNumFormat }
     * 
     */
    public AutoNumFormat createAutoNumFormat() {
        return new AutoNumFormat();
    }

    /**
     * Create an instance of {@link NoteLine }
     * 
     */
    public NoteLine createNoteLine() {
        return new NoteLine();
    }

    /**
     * Create an instance of {@link NoteSpacing }
     * 
     */
    public NoteSpacing createNoteSpacing() {
        return new NoteSpacing();
    }

    /**
     * Create an instance of {@link Numbering }
     * 
     */
    public Numbering createNumbering() {
        return new Numbering();
    }

    /**
     * Create an instance of {@link Placement }
     * 
     */
    public Placement createPlacement() {
        return new Placement();
    }

    /**
     * Create an instance of {@link EndNotePr }
     * 
     */
    public EndNotePr createEndNotePr() {
        return new EndNotePr();
    }

    /**
     * Create an instance of {@link PageBorderFill }
     * 
     */
    public PageBorderFill createPageBorderFill() {
        return new PageBorderFill();
    }

    /**
     * Create an instance of {@link Offset }
     * 
     */
    public Offset createOffset() {
        return new Offset();
    }

    /**
     * Create an instance of {@link Ctrl }
     * 
     */
    public Ctrl createCtrl() {
        return new Ctrl();
    }

    /**
     * Create an instance of {@link ColPr }
     * 
     */
    public ColPr createColPr() {
        return new ColPr();
    }

    /**
     * Create an instance of {@link T }
     * 
     */
    public T createT() {
        return new T();
    }

    /**
     * Create an instance of {@link FwSpace }
     * 
     */
    public FwSpace createFwSpace() {
        return new FwSpace();
    }

    /**
     * Create an instance of {@link LineBreak }
     * 
     */
    public LineBreak createLineBreak() {
        return new LineBreak();
    }

    /**
     * Create an instance of {@link Tbl }
     * 
     */
    public Tbl createTbl() {
        return new Tbl();
    }

    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }

    /**
     * Create an instance of {@link SubList }
     * 
     */
    public SubList createSubList() {
        return new SubList();
    }

    /**
     * Create an instance of {@link InMargin }
     * 
     */
    public InMargin createInMargin() {
        return new InMargin();
    }

    /**
     * Create an instance of {@link OutMargin }
     * 
     */
    public OutMargin createOutMargin() {
        return new OutMargin();
    }

    /**
     * Create an instance of {@link Pos }
     * 
     */
    public Pos createPos() {
        return new Pos();
    }

    /**
     * Create an instance of {@link Sz }
     * 
     */
    public Sz createSz() {
        return new Sz();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link Tc }
     * 
     */
    public Tc createTc() {
        return new Tc();
    }

    /**
     * Create an instance of {@link CellAddr }
     * 
     */
    public CellAddr createCellAddr() {
        return new CellAddr();
    }

    /**
     * Create an instance of {@link CellSpan }
     * 
     */
    public CellSpan createCellSpan() {
        return new CellSpan();
    }

    /**
     * Create an instance of {@link CellSz }
     * 
     */
    public CellSz createCellSz() {
        return new CellSz();
    }

    /**
     * Create an instance of {@link CellMargin }
     * 
     */
    public CellMargin createCellMargin() {
        return new CellMargin();
    }

    /**
     * Create an instance of {@link Linesegarray }
     * 
     */
    public Linesegarray createLinesegarray() {
        return new Linesegarray();
    }

    /**
     * Create an instance of {@link Lineseg }
     * 
     */
    public Lineseg createLineseg() {
        return new Lineseg();
    }

	
	
	

}
