//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="affectLSpacing" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="allowOverlap" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="flowWithText" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="holdAnchorAndSO" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="horzAlign" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="horzOffset" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="horzRelTo" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="treatAsChar" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="vertAlign" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="vertOffset" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="vertRelTo" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "pos")
public class Pos {

    @XmlAttribute(name = "affectLSpacing", required = true)
    protected BigInteger affectLSpacing;
    @XmlAttribute(name = "allowOverlap", required = true)
    protected BigInteger allowOverlap;
    @XmlAttribute(name = "flowWithText", required = true)
    protected BigInteger flowWithText;
    @XmlAttribute(name = "holdAnchorAndSO", required = true)
    protected BigInteger holdAnchorAndSO;
    @XmlAttribute(name = "horzAlign", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String horzAlign;
    @XmlAttribute(name = "horzOffset", required = true)
    protected BigInteger horzOffset;
    @XmlAttribute(name = "horzRelTo", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String horzRelTo;
    @XmlAttribute(name = "treatAsChar", required = true)
    protected BigInteger treatAsChar;
    @XmlAttribute(name = "vertAlign", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String vertAlign;
    @XmlAttribute(name = "vertOffset", required = true)
    protected BigInteger vertOffset;
    @XmlAttribute(name = "vertRelTo", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String vertRelTo;

    /**
     * Gets the value of the affectLSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAffectLSpacing() {
        return affectLSpacing;
    }

    /**
     * Sets the value of the affectLSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAffectLSpacing(BigInteger value) {
        this.affectLSpacing = value;
    }

    /**
     * Gets the value of the allowOverlap property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAllowOverlap() {
        return allowOverlap;
    }

    /**
     * Sets the value of the allowOverlap property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAllowOverlap(BigInteger value) {
        this.allowOverlap = value;
    }

    /**
     * Gets the value of the flowWithText property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFlowWithText() {
        return flowWithText;
    }

    /**
     * Sets the value of the flowWithText property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlowWithText(BigInteger value) {
        this.flowWithText = value;
    }

    /**
     * Gets the value of the holdAnchorAndSO property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHoldAnchorAndSO() {
        return holdAnchorAndSO;
    }

    /**
     * Sets the value of the holdAnchorAndSO property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHoldAnchorAndSO(BigInteger value) {
        this.holdAnchorAndSO = value;
    }

    /**
     * Gets the value of the horzAlign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorzAlign() {
        return horzAlign;
    }

    /**
     * Sets the value of the horzAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorzAlign(String value) {
        this.horzAlign = value;
    }

    /**
     * Gets the value of the horzOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHorzOffset() {
        return horzOffset;
    }

    /**
     * Sets the value of the horzOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHorzOffset(BigInteger value) {
        this.horzOffset = value;
    }

    /**
     * Gets the value of the horzRelTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorzRelTo() {
        return horzRelTo;
    }

    /**
     * Sets the value of the horzRelTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorzRelTo(String value) {
        this.horzRelTo = value;
    }

    /**
     * Gets the value of the treatAsChar property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTreatAsChar() {
        return treatAsChar;
    }

    /**
     * Sets the value of the treatAsChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTreatAsChar(BigInteger value) {
        this.treatAsChar = value;
    }

    /**
     * Gets the value of the vertAlign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVertAlign() {
        return vertAlign;
    }

    /**
     * Sets the value of the vertAlign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVertAlign(String value) {
        this.vertAlign = value;
    }

    /**
     * Gets the value of the vertOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVertOffset() {
        return vertOffset;
    }

    /**
     * Sets the value of the vertOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVertOffset(BigInteger value) {
        this.vertOffset = value;
    }

    /**
     * Gets the value of the vertRelTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVertRelTo() {
        return vertRelTo;
    }

    /**
     * Sets the value of the vertRelTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVertRelTo(String value) {
        this.vertRelTo = value;
    }

}
