//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}caption"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}inMargin"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}outMargin"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}pos"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}sz"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}tr"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="borderFillIDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="cellSpacing" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="colCnt" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="dropcapstyle" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="lock" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="noAdjust" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="numberingType" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="pageBreak" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="repeatHeader" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="rowCnt" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="textFlow" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="textWrap" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="zOrder" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "captionOrInMarginOrOutMargin"
})
@XmlRootElement(name = "tbl")
public class Tbl {

    @XmlElements({
        @XmlElement(name = "caption", type = Caption.class),
        @XmlElement(name = "inMargin", type = InMargin.class),
        @XmlElement(name = "outMargin", type = OutMargin.class),
        @XmlElement(name = "pos", type = Pos.class),
        @XmlElement(name = "sz", type = Sz.class),
        @XmlElement(name = "tr", type = Tr.class)
    })
    protected List<Object> captionOrInMarginOrOutMargin;
    @XmlAttribute(name = "borderFillIDRef", required = true)
    protected BigInteger borderFillIDRef;
    @XmlAttribute(name = "cellSpacing", required = true)
    protected BigInteger cellSpacing;
    @XmlAttribute(name = "colCnt", required = true)
    protected BigInteger colCnt;
    @XmlAttribute(name = "dropcapstyle", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dropcapstyle;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "lock", required = true)
    protected BigInteger lock;
    @XmlAttribute(name = "noAdjust", required = true)
    protected BigInteger noAdjust;
    @XmlAttribute(name = "numberingType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String numberingType;
    @XmlAttribute(name = "pageBreak", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pageBreak;
    @XmlAttribute(name = "repeatHeader", required = true)
    protected BigInteger repeatHeader;
    @XmlAttribute(name = "rowCnt", required = true)
    protected BigInteger rowCnt;
    @XmlAttribute(name = "textFlow", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String textFlow;
    @XmlAttribute(name = "textWrap", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String textWrap;
    @XmlAttribute(name = "zOrder", required = true)
    protected BigInteger zOrder;

    /**
     * Gets the value of the captionOrInMarginOrOutMargin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the captionOrInMarginOrOutMargin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaptionOrInMarginOrOutMargin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Caption }
     * {@link InMargin }
     * {@link OutMargin }
     * {@link Pos }
     * {@link Sz }
     * {@link Tr }
     * 
     * 
     */
    public List<Object> getCaptionOrInMarginOrOutMargin() {
        if (captionOrInMarginOrOutMargin == null) {
            captionOrInMarginOrOutMargin = new ArrayList<Object>();
        }
        return this.captionOrInMarginOrOutMargin;
    }

    /**
     * Gets the value of the borderFillIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBorderFillIDRef() {
        return borderFillIDRef;
    }

    /**
     * Sets the value of the borderFillIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBorderFillIDRef(BigInteger value) {
        this.borderFillIDRef = value;
    }

    /**
     * Gets the value of the cellSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCellSpacing() {
        return cellSpacing;
    }

    /**
     * Sets the value of the cellSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCellSpacing(BigInteger value) {
        this.cellSpacing = value;
    }

    /**
     * Gets the value of the colCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColCnt() {
        return colCnt;
    }

    /**
     * Sets the value of the colCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColCnt(BigInteger value) {
        this.colCnt = value;
    }

    /**
     * Gets the value of the dropcapstyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropcapstyle() {
        return dropcapstyle;
    }

    /**
     * Sets the value of the dropcapstyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropcapstyle(String value) {
        this.dropcapstyle = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the lock property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLock() {
        return lock;
    }

    /**
     * Sets the value of the lock property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLock(BigInteger value) {
        this.lock = value;
    }

    /**
     * Gets the value of the noAdjust property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoAdjust() {
        return noAdjust;
    }

    /**
     * Sets the value of the noAdjust property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoAdjust(BigInteger value) {
        this.noAdjust = value;
    }

    /**
     * Gets the value of the numberingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberingType() {
        return numberingType;
    }

    /**
     * Sets the value of the numberingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberingType(String value) {
        this.numberingType = value;
    }

    /**
     * Gets the value of the pageBreak property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageBreak() {
        return pageBreak;
    }

    /**
     * Sets the value of the pageBreak property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageBreak(String value) {
        this.pageBreak = value;
    }

    /**
     * Gets the value of the repeatHeader property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRepeatHeader() {
        return repeatHeader;
    }

    /**
     * Sets the value of the repeatHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRepeatHeader(BigInteger value) {
        this.repeatHeader = value;
    }

    /**
     * Gets the value of the rowCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRowCnt() {
        return rowCnt;
    }

    /**
     * Sets the value of the rowCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRowCnt(BigInteger value) {
        this.rowCnt = value;
    }

    /**
     * Gets the value of the textFlow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextFlow() {
        return textFlow;
    }

    /**
     * Sets the value of the textFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextFlow(String value) {
        this.textFlow = value;
    }

    /**
     * Gets the value of the textWrap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextWrap() {
        return textWrap;
    }

    /**
     * Sets the value of the textWrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextWrap(String value) {
        this.textWrap = value;
    }

    /**
     * Gets the value of the zOrder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getZOrder() {
        return zOrder;
    }

    /**
     * Sets the value of the zOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setZOrder(BigInteger value) {
        this.zOrder = value;
    }

}
