/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hwpx

import jakarta.xml.bind.JAXBContext
import jakarta.xml.bind.Marshaller
import jakarta.xml.bind.Unmarshaller
import java.io.StringReader
import java.io.StringWriter

import org.idpf._2007.opf


fun main() {
    ObjectFactory of = new ObjectFactory()
    Package p = of.createPackage()
}
