//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.15 at 05:28:26 AM UTC 
//


package kr.co.hancom.hwpml._2011.head;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}layoutCompatibility"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="targetProgram" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "layoutCompatibility"
})
@XmlRootElement(name = "compatibleDocument")
public class CompatibleDocument {

    @XmlElement(required = true)
    protected LayoutCompatibility layoutCompatibility;
    @XmlAttribute(name = "targetProgram", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String targetProgram;

    /**
     * Gets the value of the layoutCompatibility property.
     * 
     * @return
     *     possible object is
     *     {@link LayoutCompatibility }
     *     
     */
    public LayoutCompatibility getLayoutCompatibility() {
        return layoutCompatibility;
    }

    /**
     * Sets the value of the layoutCompatibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link LayoutCompatibility }
     *     
     */
    public void setLayoutCompatibility(LayoutCompatibility value) {
        this.layoutCompatibility = value;
    }

    /**
     * Gets the value of the targetProgram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetProgram() {
        return targetProgram;
    }

    /**
     * Sets the value of the targetProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetProgram(String value) {
        this.targetProgram = value;
    }

}
