//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.15 at 05:28:26 AM UTC 
//


package kr.co.hancom.hwpml._2011.head;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kr.co.hancom.hwpml._2011.head package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kr.co.hancom.hwpml._2011.head
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link BeginNum }
     * 
     */
    public BeginNum createBeginNum() {
        return new BeginNum();
    }

    /**
     * Create an instance of {@link RefList }
     * 
     */
    public RefList createRefList() {
        return new RefList();
    }

    /**
     * Create an instance of {@link Fontfaces }
     * 
     */
    public Fontfaces createFontfaces() {
        return new Fontfaces();
    }

    /**
     * Create an instance of {@link Fontface }
     * 
     */
    public Fontface createFontface() {
        return new Fontface();
    }

    /**
     * Create an instance of {@link Font }
     * 
     */
    public Font createFont() {
        return new Font();
    }

    /**
     * Create an instance of {@link BorderFills }
     * 
     */
    public BorderFills createBorderFills() {
        return new BorderFills();
    }

    /**
     * Create an instance of {@link BorderFill }
     * 
     */
    public BorderFill createBorderFill() {
        return new BorderFill();
    }

    /**
     * Create an instance of {@link Slash }
     * 
     */
    public Slash createSlash() {
        return new Slash();
    }

    /**
     * Create an instance of {@link BackSlash }
     * 
     */
    public BackSlash createBackSlash() {
        return new BackSlash();
    }

    /**
     * Create an instance of {@link LeftBorder }
     * 
     */
    public LeftBorder createLeftBorder() {
        return new LeftBorder();
    }

    /**
     * Create an instance of {@link RightBorder }
     * 
     */
    public RightBorder createRightBorder() {
        return new RightBorder();
    }

    /**
     * Create an instance of {@link TopBorder }
     * 
     */
    public TopBorder createTopBorder() {
        return new TopBorder();
    }

    /**
     * Create an instance of {@link BottomBorder }
     * 
     */
    public BottomBorder createBottomBorder() {
        return new BottomBorder();
    }

    /**
     * Create an instance of {@link Diagonal }
     * 
     */
    public Diagonal createDiagonal() {
        return new Diagonal();
    }

    /**
     * Create an instance of {@link CharProperties }
     * 
     */
    public CharProperties createCharProperties() {
        return new CharProperties();
    }

    /**
     * Create an instance of {@link CharPr }
     * 
     */
    public CharPr createCharPr() {
        return new CharPr();
    }

    /**
     * Create an instance of {@link FontRef }
     * 
     */
    public FontRef createFontRef() {
        return new FontRef();
    }

    /**
     * Create an instance of {@link Ratio }
     * 
     */
    public Ratio createRatio() {
        return new Ratio();
    }

    /**
     * Create an instance of {@link Spacing }
     * 
     */
    public Spacing createSpacing() {
        return new Spacing();
    }

    /**
     * Create an instance of {@link RelSz }
     * 
     */
    public RelSz createRelSz() {
        return new RelSz();
    }

    /**
     * Create an instance of {@link Offset }
     * 
     */
    public Offset createOffset() {
        return new Offset();
    }

    /**
     * Create an instance of {@link TabProperties }
     * 
     */
    public TabProperties createTabProperties() {
        return new TabProperties();
    }

    /**
     * Create an instance of {@link TabPr }
     * 
     */
    public TabPr createTabPr() {
        return new TabPr();
    }

    /**
     * Create an instance of {@link Numberings }
     * 
     */
    public Numberings createNumberings() {
        return new Numberings();
    }

    /**
     * Create an instance of {@link Numbering }
     * 
     */
    public Numbering createNumbering() {
        return new Numbering();
    }

    /**
     * Create an instance of {@link ParaHead }
     * 
     */
    public ParaHead createParaHead() {
        return new ParaHead();
    }

    /**
     * Create an instance of {@link ParaProperties }
     * 
     */
    public ParaProperties createParaProperties() {
        return new ParaProperties();
    }

    /**
     * Create an instance of {@link ParaPr }
     * 
     */
    public ParaPr createParaPr() {
        return new ParaPr();
    }

    /**
     * Create an instance of {@link Align }
     * 
     */
    public Align createAlign() {
        return new Align();
    }

    /**
     * Create an instance of {@link Heading }
     * 
     */
    public Heading createHeading() {
        return new Heading();
    }

    /**
     * Create an instance of {@link BreakSetting }
     * 
     */
    public BreakSetting createBreakSetting() {
        return new BreakSetting();
    }

    /**
     * Create an instance of {@link AutoSpacing }
     * 
     */
    public AutoSpacing createAutoSpacing() {
        return new AutoSpacing();
    }

    /**
     * Create an instance of {@link Margin }
     * 
     */
    public Margin createMargin() {
        return new Margin();
    }

    /**
     * Create an instance of {@link LineSpacing }
     * 
     */
    public LineSpacing createLineSpacing() {
        return new LineSpacing();
    }

    /**
     * Create an instance of {@link Border }
     * 
     */
    public Border createBorder() {
        return new Border();
    }

    /**
     * Create an instance of {@link Styles }
     * 
     */
    public Styles createStyles() {
        return new Styles();
    }

    /**
     * Create an instance of {@link Style }
     * 
     */
    public Style createStyle() {
        return new Style();
    }

    /**
     * Create an instance of {@link CompatibleDocument }
     * 
     */
    public CompatibleDocument createCompatibleDocument() {
        return new CompatibleDocument();
    }

    /**
     * Create an instance of {@link LayoutCompatibility }
     * 
     */
    public LayoutCompatibility createLayoutCompatibility() {
        return new LayoutCompatibility();
    }

    /**
     * Create an instance of {@link DocOption }
     * 
     */
    public DocOption createDocOption() {
        return new DocOption();
    }

    /**
     * Create an instance of {@link Linkinfo }
     * 
     */
    public Linkinfo createLinkinfo() {
        return new Linkinfo();
    }

    /**
     * Create an instance of {@link TrackchageConfig }
     * 
     */
    public TrackchageConfig createTrackchageConfig() {
        return new TrackchageConfig();
    }

}
