//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.03 at 11:51:35 AM UTC 
//


package kr.co.hancom.hwpml._2011.head;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import kr.co.hancom.hwpml._2011.core.FillBrush;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}slash"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}backSlash"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}leftBorder"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}rightBorder"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}topBorder"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}bottomBorder"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}diagonal" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/core}fillBrush" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="breakCellSeparateLine" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="centerLine" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="shadow" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="threeD" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "slash",
    "backSlash",
    "leftBorder",
    "rightBorder",
    "topBorder",
    "bottomBorder",
    "diagonal",
    "fillBrush"
})
@XmlRootElement(name = "borderFill")
public class BorderFill {

    @XmlElement(required = true)
    protected Slash slash;
    @XmlElement(required = true)
    protected BackSlash backSlash;
    @XmlElement(required = true)
    protected LeftBorder leftBorder;
    @XmlElement(required = true)
    protected RightBorder rightBorder;
    @XmlElement(required = true)
    protected TopBorder topBorder;
    @XmlElement(required = true)
    protected BottomBorder bottomBorder;
    protected Diagonal diagonal;
    @XmlElement(namespace = "http://www.hancom.co.kr/hwpml/2011/core")
    protected FillBrush fillBrush;
    @XmlAttribute(name = "breakCellSeparateLine", required = true)
    protected BigInteger breakCellSeparateLine;
    @XmlAttribute(name = "centerLine", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String centerLine;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "shadow", required = true)
    protected BigInteger shadow;
    @XmlAttribute(name = "threeD", required = true)
    protected BigInteger threeD;

    /**
     * Gets the value of the slash property.
     * 
     * @return
     *     possible object is
     *     {@link Slash }
     *     
     */
    public Slash getSlash() {
        return slash;
    }

    /**
     * Sets the value of the slash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Slash }
     *     
     */
    public void setSlash(Slash value) {
        this.slash = value;
    }

    /**
     * Gets the value of the backSlash property.
     * 
     * @return
     *     possible object is
     *     {@link BackSlash }
     *     
     */
    public BackSlash getBackSlash() {
        return backSlash;
    }

    /**
     * Sets the value of the backSlash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackSlash }
     *     
     */
    public void setBackSlash(BackSlash value) {
        this.backSlash = value;
    }

    /**
     * Gets the value of the leftBorder property.
     * 
     * @return
     *     possible object is
     *     {@link LeftBorder }
     *     
     */
    public LeftBorder getLeftBorder() {
        return leftBorder;
    }

    /**
     * Sets the value of the leftBorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeftBorder }
     *     
     */
    public void setLeftBorder(LeftBorder value) {
        this.leftBorder = value;
    }

    /**
     * Gets the value of the rightBorder property.
     * 
     * @return
     *     possible object is
     *     {@link RightBorder }
     *     
     */
    public RightBorder getRightBorder() {
        return rightBorder;
    }

    /**
     * Sets the value of the rightBorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link RightBorder }
     *     
     */
    public void setRightBorder(RightBorder value) {
        this.rightBorder = value;
    }

    /**
     * Gets the value of the topBorder property.
     * 
     * @return
     *     possible object is
     *     {@link TopBorder }
     *     
     */
    public TopBorder getTopBorder() {
        return topBorder;
    }

    /**
     * Sets the value of the topBorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopBorder }
     *     
     */
    public void setTopBorder(TopBorder value) {
        this.topBorder = value;
    }

    /**
     * Gets the value of the bottomBorder property.
     * 
     * @return
     *     possible object is
     *     {@link BottomBorder }
     *     
     */
    public BottomBorder getBottomBorder() {
        return bottomBorder;
    }

    /**
     * Sets the value of the bottomBorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BottomBorder }
     *     
     */
    public void setBottomBorder(BottomBorder value) {
        this.bottomBorder = value;
    }

    /**
     * Gets the value of the diagonal property.
     * 
     * @return
     *     possible object is
     *     {@link Diagonal }
     *     
     */
    public Diagonal getDiagonal() {
        return diagonal;
    }

    /**
     * Sets the value of the diagonal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Diagonal }
     *     
     */
    public void setDiagonal(Diagonal value) {
        this.diagonal = value;
    }

    /**
     * Gets the value of the fillBrush property.
     * 
     * @return
     *     possible object is
     *     {@link FillBrush }
     *     
     */
    public FillBrush getFillBrush() {
        return fillBrush;
    }

    /**
     * Sets the value of the fillBrush property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillBrush }
     *     
     */
    public void setFillBrush(FillBrush value) {
        this.fillBrush = value;
    }

    /**
     * Gets the value of the breakCellSeparateLine property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBreakCellSeparateLine() {
        return breakCellSeparateLine;
    }

    /**
     * Sets the value of the breakCellSeparateLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBreakCellSeparateLine(BigInteger value) {
        this.breakCellSeparateLine = value;
    }

    /**
     * Gets the value of the centerLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenterLine() {
        return centerLine;
    }

    /**
     * Sets the value of the centerLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenterLine(String value) {
        this.centerLine = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the shadow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShadow() {
        return shadow;
    }

    /**
     * Sets the value of the shadow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShadow(BigInteger value) {
        this.shadow = value;
    }

    /**
     * Gets the value of the threeD property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThreeD() {
        return threeD;
    }

    /**
     * Sets the value of the threeD property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThreeD(BigInteger value) {
        this.threeD = value;
    }

}
