//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.03 at 11:51:35 AM UTC 
//


package kr.co.hancom.hwpml._2011.head;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="borderFillIDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="connect" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="ignoreMargin" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="offsetBottom" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="offsetLeft" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="offsetRight" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="offsetTop" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "border")
public class Border {

    @XmlAttribute(name = "borderFillIDRef", required = true)
    protected BigInteger borderFillIDRef;
    @XmlAttribute(name = "connect", required = true)
    protected BigInteger connect;
    @XmlAttribute(name = "ignoreMargin", required = true)
    protected BigInteger ignoreMargin;
    @XmlAttribute(name = "offsetBottom", required = true)
    protected BigInteger offsetBottom;
    @XmlAttribute(name = "offsetLeft", required = true)
    protected BigInteger offsetLeft;
    @XmlAttribute(name = "offsetRight", required = true)
    protected BigInteger offsetRight;
    @XmlAttribute(name = "offsetTop", required = true)
    protected BigInteger offsetTop;

    /**
     * Gets the value of the borderFillIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBorderFillIDRef() {
        return borderFillIDRef;
    }

    /**
     * Sets the value of the borderFillIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBorderFillIDRef(BigInteger value) {
        this.borderFillIDRef = value;
    }

    /**
     * Gets the value of the connect property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConnect() {
        return connect;
    }

    /**
     * Sets the value of the connect property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConnect(BigInteger value) {
        this.connect = value;
    }

    /**
     * Gets the value of the ignoreMargin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIgnoreMargin() {
        return ignoreMargin;
    }

    /**
     * Sets the value of the ignoreMargin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIgnoreMargin(BigInteger value) {
        this.ignoreMargin = value;
    }

    /**
     * Gets the value of the offsetBottom property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOffsetBottom() {
        return offsetBottom;
    }

    /**
     * Sets the value of the offsetBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOffsetBottom(BigInteger value) {
        this.offsetBottom = value;
    }

    /**
     * Gets the value of the offsetLeft property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOffsetLeft() {
        return offsetLeft;
    }

    /**
     * Sets the value of the offsetLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOffsetLeft(BigInteger value) {
        this.offsetLeft = value;
    }

    /**
     * Gets the value of the offsetRight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOffsetRight() {
        return offsetRight;
    }

    /**
     * Sets the value of the offsetRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOffsetRight(BigInteger value) {
        this.offsetRight = value;
    }

    /**
     * Gets the value of the offsetTop property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOffsetTop() {
        return offsetTop;
    }

    /**
     * Sets the value of the offsetTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOffsetTop(BigInteger value) {
        this.offsetTop = value;
    }

}
