//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.03 at 11:51:35 AM UTC 
//


package kr.co.hancom.hwpml._2011.head;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import kr.co.hancom.hwpml._2011.paragraph.Switch;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}align"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}heading"/&gt;
 *           &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}switch"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}breakSetting"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}autoSpacing"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}margin"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}lineSpacing"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/head}border"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="checked" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="condense" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="fontLineHeight" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="snapToGrid" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="suppressLineNumbers" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="tabPrIDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "align",
    "heading",
    "_switch",
    "breakSetting",
    "autoSpacing",
    "margin",
    "lineSpacing",
    "border"
})
@XmlRootElement(name = "paraPr")
public class ParaPr {

    @XmlElement(required = true)
    protected Align align;
    protected Heading heading;
    @XmlElement(name = "switch", namespace = "http://www.hancom.co.kr/hwpml/2011/paragraph")
    protected Switch _switch;
    @XmlElement(required = true)
    protected BreakSetting breakSetting;
    @XmlElement(required = true)
    protected AutoSpacing autoSpacing;
    @XmlElement(required = true)
    protected Margin margin;
    @XmlElement(required = true)
    protected LineSpacing lineSpacing;
    @XmlElement(required = true)
    protected Border border;
    @XmlAttribute(name = "checked", required = true)
    protected BigInteger checked;
    @XmlAttribute(name = "condense", required = true)
    protected BigInteger condense;
    @XmlAttribute(name = "fontLineHeight", required = true)
    protected BigInteger fontLineHeight;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "snapToGrid", required = true)
    protected BigInteger snapToGrid;
    @XmlAttribute(name = "suppressLineNumbers", required = true)
    protected BigInteger suppressLineNumbers;
    @XmlAttribute(name = "tabPrIDRef", required = true)
    protected BigInteger tabPrIDRef;

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link Align }
     *     
     */
    public Align getAlign() {
        return align;
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link Align }
     *     
     */
    public void setAlign(Align value) {
        this.align = value;
    }

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link Heading }
     *     
     */
    public Heading getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link Heading }
     *     
     */
    public void setHeading(Heading value) {
        this.heading = value;
    }

    /**
     * Gets the value of the switch property.
     * 
     * @return
     *     possible object is
     *     {@link Switch }
     *     
     */
    public Switch getSwitch() {
        return _switch;
    }

    /**
     * Sets the value of the switch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Switch }
     *     
     */
    public void setSwitch(Switch value) {
        this._switch = value;
    }

    /**
     * Gets the value of the breakSetting property.
     * 
     * @return
     *     possible object is
     *     {@link BreakSetting }
     *     
     */
    public BreakSetting getBreakSetting() {
        return breakSetting;
    }

    /**
     * Sets the value of the breakSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link BreakSetting }
     *     
     */
    public void setBreakSetting(BreakSetting value) {
        this.breakSetting = value;
    }

    /**
     * Gets the value of the autoSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link AutoSpacing }
     *     
     */
    public AutoSpacing getAutoSpacing() {
        return autoSpacing;
    }

    /**
     * Sets the value of the autoSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutoSpacing }
     *     
     */
    public void setAutoSpacing(AutoSpacing value) {
        this.autoSpacing = value;
    }

    /**
     * Gets the value of the margin property.
     * 
     * @return
     *     possible object is
     *     {@link Margin }
     *     
     */
    public Margin getMargin() {
        return margin;
    }

    /**
     * Sets the value of the margin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Margin }
     *     
     */
    public void setMargin(Margin value) {
        this.margin = value;
    }

    /**
     * Gets the value of the lineSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link LineSpacing }
     *     
     */
    public LineSpacing getLineSpacing() {
        return lineSpacing;
    }

    /**
     * Sets the value of the lineSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineSpacing }
     *     
     */
    public void setLineSpacing(LineSpacing value) {
        this.lineSpacing = value;
    }

    /**
     * Gets the value of the border property.
     * 
     * @return
     *     possible object is
     *     {@link Border }
     *     
     */
    public Border getBorder() {
        return border;
    }

    /**
     * Sets the value of the border property.
     * 
     * @param value
     *     allowed object is
     *     {@link Border }
     *     
     */
    public void setBorder(Border value) {
        this.border = value;
    }

    /**
     * Gets the value of the checked property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChecked() {
        return checked;
    }

    /**
     * Sets the value of the checked property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChecked(BigInteger value) {
        this.checked = value;
    }

    /**
     * Gets the value of the condense property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCondense() {
        return condense;
    }

    /**
     * Sets the value of the condense property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCondense(BigInteger value) {
        this.condense = value;
    }

    /**
     * Gets the value of the fontLineHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFontLineHeight() {
        return fontLineHeight;
    }

    /**
     * Sets the value of the fontLineHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFontLineHeight(BigInteger value) {
        this.fontLineHeight = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the snapToGrid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSnapToGrid() {
        return snapToGrid;
    }

    /**
     * Sets the value of the snapToGrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSnapToGrid(BigInteger value) {
        this.snapToGrid = value;
    }

    /**
     * Gets the value of the suppressLineNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSuppressLineNumbers() {
        return suppressLineNumbers;
    }

    /**
     * Sets the value of the suppressLineNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSuppressLineNumbers(BigInteger value) {
        this.suppressLineNumbers = value;
    }

    /**
     * Gets the value of the tabPrIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTabPrIDRef() {
        return tabPrIDRef;
    }

    /**
     * Sets the value of the tabPrIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTabPrIDRef(BigInteger value) {
        this.tabPrIDRef = value;
    }

}
