//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}run" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}linesegarray"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="columnBreak" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="merged" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="pageBreak" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="paraPrIDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="styleIDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "run",
    "linesegarray"
})
@XmlRootElement(name = "p")
public class P {

    protected List<Run> run;
    @XmlElement(required = true)
    protected Linesegarray linesegarray;
    @XmlAttribute(name = "columnBreak", required = true)
    protected BigInteger columnBreak;
    @XmlAttribute(name = "id", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "merged", required = true)
    protected BigInteger merged;
    @XmlAttribute(name = "pageBreak", required = true)
    protected BigInteger pageBreak;
    @XmlAttribute(name = "paraPrIDRef", required = true)
    protected BigInteger paraPrIDRef;
    @XmlAttribute(name = "styleIDRef", required = true)
    protected BigInteger styleIDRef;

    /**
     * Gets the value of the run property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the run property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRun().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Run }
     * 
     * 
     */
    public List<Run> getRun() {
        if (run == null) {
            run = new ArrayList<Run>();
        }
        return this.run;
    }

    /**
     * Gets the value of the linesegarray property.
     * 
     * @return
     *     possible object is
     *     {@link Linesegarray }
     *     
     */
    public Linesegarray getLinesegarray() {
        return linesegarray;
    }

    /**
     * Sets the value of the linesegarray property.
     * 
     * @param value
     *     allowed object is
     *     {@link Linesegarray }
     *     
     */
    public void setLinesegarray(Linesegarray value) {
        this.linesegarray = value;
    }

    /**
     * Gets the value of the columnBreak property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColumnBreak() {
        return columnBreak;
    }

    /**
     * Sets the value of the columnBreak property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColumnBreak(BigInteger value) {
        this.columnBreak = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the merged property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMerged() {
        return merged;
    }

    /**
     * Sets the value of the merged property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMerged(BigInteger value) {
        this.merged = value;
    }

    /**
     * Gets the value of the pageBreak property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPageBreak() {
        return pageBreak;
    }

    /**
     * Sets the value of the pageBreak property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPageBreak(BigInteger value) {
        this.pageBreak = value;
    }

    /**
     * Gets the value of the paraPrIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParaPrIDRef() {
        return paraPrIDRef;
    }

    /**
     * Sets the value of the paraPrIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParaPrIDRef(BigInteger value) {
        this.paraPrIDRef = value;
    }

    /**
     * Gets the value of the styleIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStyleIDRef() {
        return styleIDRef;
    }

    /**
     * Sets the value of the styleIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStyleIDRef(BigInteger value) {
        this.styleIDRef = value;
    }

}
