//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hancom.co.kr/hwpml/2011/paragraph", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package kr.co.hancom.hwpml._2011.paragraph;
