//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="prefixChar" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="suffixChar" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="supscript" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="userChar" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "autoNumFormat")
public class AutoNumFormat {

    @XmlAttribute(name = "prefixChar", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String prefixChar;
    @XmlAttribute(name = "suffixChar", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String suffixChar;
    @XmlAttribute(name = "supscript", required = true)
    protected BigInteger supscript;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;
    @XmlAttribute(name = "userChar", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String userChar;

    /**
     * Gets the value of the prefixChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefixChar() {
        return prefixChar;
    }

    /**
     * Sets the value of the prefixChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefixChar(String value) {
        this.prefixChar = value;
    }

    /**
     * Gets the value of the suffixChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffixChar() {
        return suffixChar;
    }

    /**
     * Sets the value of the suffixChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffixChar(String value) {
        this.suffixChar = value;
    }

    /**
     * Gets the value of the supscript property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSupscript() {
        return supscript;
    }

    /**
     * Sets the value of the supscript property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSupscript(BigInteger value) {
        this.supscript = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the userChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserChar() {
        return userChar;
    }

    /**
     * Sets the value of the userChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserChar(String value) {
        this.userChar = value;
    }

}
