//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}autoNumFormat"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}noteLine"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}noteSpacing"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}numbering"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}placement"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "autoNumFormat",
    "noteLine",
    "noteSpacing",
    "numbering",
    "placement"
})
@XmlRootElement(name = "footNotePr")
public class FootNotePr {

    @XmlElement(required = true)
    protected AutoNumFormat autoNumFormat;
    @XmlElement(required = true)
    protected NoteLine noteLine;
    @XmlElement(required = true)
    protected NoteSpacing noteSpacing;
    @XmlElement(required = true)
    protected Numbering numbering;
    @XmlElement(required = true)
    protected Placement placement;

    /**
     * Gets the value of the autoNumFormat property.
     * 
     * @return
     *     possible object is
     *     {@link AutoNumFormat }
     *     
     */
    public AutoNumFormat getAutoNumFormat() {
        return autoNumFormat;
    }

    /**
     * Sets the value of the autoNumFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link AutoNumFormat }
     *     
     */
    public void setAutoNumFormat(AutoNumFormat value) {
        this.autoNumFormat = value;
    }

    /**
     * Gets the value of the noteLine property.
     * 
     * @return
     *     possible object is
     *     {@link NoteLine }
     *     
     */
    public NoteLine getNoteLine() {
        return noteLine;
    }

    /**
     * Sets the value of the noteLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteLine }
     *     
     */
    public void setNoteLine(NoteLine value) {
        this.noteLine = value;
    }

    /**
     * Gets the value of the noteSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link NoteSpacing }
     *     
     */
    public NoteSpacing getNoteSpacing() {
        return noteSpacing;
    }

    /**
     * Sets the value of the noteSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoteSpacing }
     *     
     */
    public void setNoteSpacing(NoteSpacing value) {
        this.noteSpacing = value;
    }

    /**
     * Gets the value of the numbering property.
     * 
     * @return
     *     possible object is
     *     {@link Numbering }
     *     
     */
    public Numbering getNumbering() {
        return numbering;
    }

    /**
     * Sets the value of the numbering property.
     * 
     * @param value
     *     allowed object is
     *     {@link Numbering }
     *     
     */
    public void setNumbering(Numbering value) {
        this.numbering = value;
    }

    /**
     * Gets the value of the placement property.
     * 
     * @return
     *     possible object is
     *     {@link Placement }
     *     
     */
    public Placement getPlacement() {
        return placement;
    }

    /**
     * Sets the value of the placement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Placement }
     *     
     */
    public void setPlacement(Placement value) {
        this.placement = value;
    }

}
