//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}secPr"/&gt;
 *           &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}ctrl"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}t"/&gt;
 *           &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}tbl"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="charPrIDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "secPr",
    "ctrl",
    "tOrTbl"
})
@XmlRootElement(name = "run")
public class Run {

    protected SecPr secPr;
    protected Ctrl ctrl;
    @XmlElements({
        @XmlElement(name = "t", type = T.class),
        @XmlElement(name = "tbl", type = Tbl.class)
    })
    protected List<Object> tOrTbl;
    @XmlAttribute(name = "charPrIDRef", required = true)
    protected BigInteger charPrIDRef;

    /**
     * Gets the value of the secPr property.
     * 
     * @return
     *     possible object is
     *     {@link SecPr }
     *     
     */
    public SecPr getSecPr() {
        return secPr;
    }

    /**
     * Sets the value of the secPr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecPr }
     *     
     */
    public void setSecPr(SecPr value) {
        this.secPr = value;
    }

    /**
     * Gets the value of the ctrl property.
     * 
     * @return
     *     possible object is
     *     {@link Ctrl }
     *     
     */
    public Ctrl getCtrl() {
        return ctrl;
    }

    /**
     * Sets the value of the ctrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ctrl }
     *     
     */
    public void setCtrl(Ctrl value) {
        this.ctrl = value;
    }

    /**
     * Gets the value of the tOrTbl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tOrTbl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTOrTbl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link T }
     * {@link Tbl }
     * 
     * 
     */
    public List<Object> getTOrTbl() {
        if (tOrTbl == null) {
            tOrTbl = new ArrayList<Object>();
        }
        return this.tOrTbl;
    }

    /**
     * Gets the value of the charPrIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCharPrIDRef() {
        return charPrIDRef;
    }

    /**
     * Sets the value of the charPrIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCharPrIDRef(BigInteger value) {
        this.charPrIDRef = value;
    }

}
