//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}grid"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}startNum"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}visibility"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}lineNumberShape"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}pagePr"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}footNotePr"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}endNotePr"/&gt;
 *         &lt;element ref="{http://www.hancom.co.kr/hwpml/2011/paragraph}pageBorderFill" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="masterPageCnt" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="memoShapeIDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="outlineShapeIDRef" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="spaceColumns" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="tabStop" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="textDirection" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="textVerticalWidthHead" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "grid",
    "startNum",
    "visibility",
    "lineNumberShape",
    "pagePr",
    "footNotePr",
    "endNotePr",
    "pageBorderFill"
})
@XmlRootElement(name = "secPr")
public class SecPr {

    @XmlElement(required = true)
    protected Grid grid;
    @XmlElement(required = true)
    protected StartNum startNum;
    @XmlElement(required = true)
    protected Visibility visibility;
    @XmlElement(required = true)
    protected LineNumberShape lineNumberShape;
    @XmlElement(required = true)
    protected PagePr pagePr;
    @XmlElement(required = true)
    protected FootNotePr footNotePr;
    @XmlElement(required = true)
    protected EndNotePr endNotePr;
    @XmlElement(required = true)
    protected List<PageBorderFill> pageBorderFill;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;
    @XmlAttribute(name = "masterPageCnt", required = true)
    protected BigInteger masterPageCnt;
    @XmlAttribute(name = "memoShapeIDRef", required = true)
    protected BigInteger memoShapeIDRef;
    @XmlAttribute(name = "outlineShapeIDRef", required = true)
    protected BigInteger outlineShapeIDRef;
    @XmlAttribute(name = "spaceColumns", required = true)
    protected BigInteger spaceColumns;
    @XmlAttribute(name = "tabStop", required = true)
    protected BigInteger tabStop;
    @XmlAttribute(name = "textDirection", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String textDirection;
    @XmlAttribute(name = "textVerticalWidthHead", required = true)
    protected BigInteger textVerticalWidthHead;

    /**
     * Gets the value of the grid property.
     * 
     * @return
     *     possible object is
     *     {@link Grid }
     *     
     */
    public Grid getGrid() {
        return grid;
    }

    /**
     * Sets the value of the grid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Grid }
     *     
     */
    public void setGrid(Grid value) {
        this.grid = value;
    }

    /**
     * Gets the value of the startNum property.
     * 
     * @return
     *     possible object is
     *     {@link StartNum }
     *     
     */
    public StartNum getStartNum() {
        return startNum;
    }

    /**
     * Sets the value of the startNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartNum }
     *     
     */
    public void setStartNum(StartNum value) {
        this.startNum = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link Visibility }
     *     
     */
    public Visibility getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link Visibility }
     *     
     */
    public void setVisibility(Visibility value) {
        this.visibility = value;
    }

    /**
     * Gets the value of the lineNumberShape property.
     * 
     * @return
     *     possible object is
     *     {@link LineNumberShape }
     *     
     */
    public LineNumberShape getLineNumberShape() {
        return lineNumberShape;
    }

    /**
     * Sets the value of the lineNumberShape property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineNumberShape }
     *     
     */
    public void setLineNumberShape(LineNumberShape value) {
        this.lineNumberShape = value;
    }

    /**
     * Gets the value of the pagePr property.
     * 
     * @return
     *     possible object is
     *     {@link PagePr }
     *     
     */
    public PagePr getPagePr() {
        return pagePr;
    }

    /**
     * Sets the value of the pagePr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagePr }
     *     
     */
    public void setPagePr(PagePr value) {
        this.pagePr = value;
    }

    /**
     * Gets the value of the footNotePr property.
     * 
     * @return
     *     possible object is
     *     {@link FootNotePr }
     *     
     */
    public FootNotePr getFootNotePr() {
        return footNotePr;
    }

    /**
     * Sets the value of the footNotePr property.
     * 
     * @param value
     *     allowed object is
     *     {@link FootNotePr }
     *     
     */
    public void setFootNotePr(FootNotePr value) {
        this.footNotePr = value;
    }

    /**
     * Gets the value of the endNotePr property.
     * 
     * @return
     *     possible object is
     *     {@link EndNotePr }
     *     
     */
    public EndNotePr getEndNotePr() {
        return endNotePr;
    }

    /**
     * Sets the value of the endNotePr property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndNotePr }
     *     
     */
    public void setEndNotePr(EndNotePr value) {
        this.endNotePr = value;
    }

    /**
     * Gets the value of the pageBorderFill property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pageBorderFill property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPageBorderFill().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PageBorderFill }
     * 
     * 
     */
    public List<PageBorderFill> getPageBorderFill() {
        if (pageBorderFill == null) {
            pageBorderFill = new ArrayList<PageBorderFill>();
        }
        return this.pageBorderFill;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the masterPageCnt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMasterPageCnt() {
        return masterPageCnt;
    }

    /**
     * Sets the value of the masterPageCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMasterPageCnt(BigInteger value) {
        this.masterPageCnt = value;
    }

    /**
     * Gets the value of the memoShapeIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMemoShapeIDRef() {
        return memoShapeIDRef;
    }

    /**
     * Sets the value of the memoShapeIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMemoShapeIDRef(BigInteger value) {
        this.memoShapeIDRef = value;
    }

    /**
     * Gets the value of the outlineShapeIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutlineShapeIDRef() {
        return outlineShapeIDRef;
    }

    /**
     * Sets the value of the outlineShapeIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutlineShapeIDRef(BigInteger value) {
        this.outlineShapeIDRef = value;
    }

    /**
     * Gets the value of the spaceColumns property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpaceColumns() {
        return spaceColumns;
    }

    /**
     * Sets the value of the spaceColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpaceColumns(BigInteger value) {
        this.spaceColumns = value;
    }

    /**
     * Gets the value of the tabStop property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTabStop() {
        return tabStop;
    }

    /**
     * Sets the value of the tabStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTabStop(BigInteger value) {
        this.tabStop = value;
    }

    /**
     * Gets the value of the textDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextDirection() {
        return textDirection;
    }

    /**
     * Sets the value of the textDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextDirection(String value) {
        this.textDirection = value;
    }

    /**
     * Gets the value of the textVerticalWidthHead property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTextVerticalWidthHead() {
        return textVerticalWidthHead;
    }

    /**
     * Sets the value of the textVerticalWidthHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTextVerticalWidthHead(BigInteger value) {
        this.textVerticalWidthHead = value;
    }

}
