//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.04 at 01:47:45 AM UTC 
//


package kr.co.hancom.hwpml._2011.paragraph;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="border" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="fill" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" /&gt;
 *       &lt;attribute name="hideFirstEmptyLine" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="hideFirstFooter" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="hideFirstHeader" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="hideFirstMasterPage" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="hideFirstPageNum" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="showLineNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "visibility")
public class Visibility {

    @XmlAttribute(name = "border", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String border;
    @XmlAttribute(name = "fill", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fill;
    @XmlAttribute(name = "hideFirstEmptyLine", required = true)
    protected BigInteger hideFirstEmptyLine;
    @XmlAttribute(name = "hideFirstFooter", required = true)
    protected BigInteger hideFirstFooter;
    @XmlAttribute(name = "hideFirstHeader", required = true)
    protected BigInteger hideFirstHeader;
    @XmlAttribute(name = "hideFirstMasterPage", required = true)
    protected BigInteger hideFirstMasterPage;
    @XmlAttribute(name = "hideFirstPageNum", required = true)
    protected BigInteger hideFirstPageNum;
    @XmlAttribute(name = "showLineNumber", required = true)
    protected BigInteger showLineNumber;

    /**
     * Gets the value of the border property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBorder() {
        return border;
    }

    /**
     * Sets the value of the border property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBorder(String value) {
        this.border = value;
    }

    /**
     * Gets the value of the fill property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFill() {
        return fill;
    }

    /**
     * Sets the value of the fill property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFill(String value) {
        this.fill = value;
    }

    /**
     * Gets the value of the hideFirstEmptyLine property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHideFirstEmptyLine() {
        return hideFirstEmptyLine;
    }

    /**
     * Sets the value of the hideFirstEmptyLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHideFirstEmptyLine(BigInteger value) {
        this.hideFirstEmptyLine = value;
    }

    /**
     * Gets the value of the hideFirstFooter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHideFirstFooter() {
        return hideFirstFooter;
    }

    /**
     * Sets the value of the hideFirstFooter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHideFirstFooter(BigInteger value) {
        this.hideFirstFooter = value;
    }

    /**
     * Gets the value of the hideFirstHeader property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHideFirstHeader() {
        return hideFirstHeader;
    }

    /**
     * Sets the value of the hideFirstHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHideFirstHeader(BigInteger value) {
        this.hideFirstHeader = value;
    }

    /**
     * Gets the value of the hideFirstMasterPage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHideFirstMasterPage() {
        return hideFirstMasterPage;
    }

    /**
     * Sets the value of the hideFirstMasterPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHideFirstMasterPage(BigInteger value) {
        this.hideFirstMasterPage = value;
    }

    /**
     * Gets the value of the hideFirstPageNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHideFirstPageNum() {
        return hideFirstPageNum;
    }

    /**
     * Sets the value of the hideFirstPageNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHideFirstPageNum(BigInteger value) {
        this.hideFirstPageNum = value;
    }

    /**
     * Gets the value of the showLineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShowLineNumber() {
        return showLineNumber;
    }

    /**
     * Sets the value of the showLineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShowLineNumber(BigInteger value) {
        this.showLineNumber = value;
    }

}
